<?php
// Generated from allVoices of JacRed 3.16.0
// (FileDB.Metadata.cs) and our lists there: key (lower case, words joined by
// a space) -> the name shown, '' for a common word never shown.

define('AIO_VOICES_NGRAM', 4);   // words in the longest key

function aio_voices_dict()
{
    static $d = array(
        '1+1' => '1+1', '100 тв' => '100 ТВ', '1001 cinema' => '1001cinema', '1001cinema' => '1001cinema',
        '2+2' => '2+2', '2x2' => '2x2', '2х2' => '2x2', '3 крапки' => 'Три Крапки', '3df' => '3df voice',
        '3df voice' => '3df voice', '4u2ges' => '4u2ges', '5 й канал спб' => '5-й канал СПб',
        '5 канал' => '5 канал', 'a gavrilov' => 'А. Гаврилов', 'a lazarchuk' => 'A. Lazarchuk',
        'a marchenko' => 'А. Марченко', 'a tolstobrov' => 'А. Толстобров', 'aaa sound' => 'AAA-Sound',
        'aaasound' => 'AAA-Sound', 'ab video' => 'AB-Video', 'adisound' => 'AdiSound',
        'adrianzp' => 'AdrianZP', 'agatha studdio' => 'Agatha Studdio', 'aimaksaltv' => 'AimaksaLTV',
        'aleks kv' => 'ALEKS KV', 'alexfilm' => 'AlexFilm', 'alezan' => 'Alezan',
        'alphaproject' => 'AlphaProject', 'alternative production' => 'Alternative Production',
        'amalgam' => 'Amalgam', 'amalgama' => 'Амальгама', 'amanogawa' => 'Amanogawa',
        'amazing dubbing' => 'Amazing Dubbing', 'amber' => 'Amber', 'amedia' => 'Amedia', 'ams' => 'AMS',
        'ancord' => 'Ancord', 'andre1288' => 'Andre1288', 'anibaza' => 'AniBaza', 'anidub' => 'AniDUB',
        'anifilm' => 'AniFilm', 'anika' => 'Anika', 'aniliberty' => 'AniLiberty', 'anilibria' => 'AniLibria',
        'anilibria tv' => 'AniLibria', 'animaunt' => 'AniMaunt', 'animedia' => 'AniMedia',
        'animedub' => 'Animedub', 'animegroup' => 'Animegroup', 'animereactor' => 'AnimeReactor',
        'animespace team' => 'AnimeSpace Team', 'aniplague' => 'AniPlague', 'anistar' => 'AniStar',
        'aniua' => 'AniUA', 'anivoice' => 'ANIvoice', 'aniwayt' => 'AniWayt', 'anubis' => 'Anubis',
        'anyfilm' => 'AnyFilm', 'anything group' => 'Anything-group', 'apofysteam' => 'ApofysTeam',
        'arasi project' => 'Arasi project', 'arisu' => 'Arisu', 'arru workshop' => 'ARRU Workshop',
        'artymko' => 'ArtymKo', 'asian miracle group' => 'Asian Miracle Group', 'astana tv' => 'Astana TV',
        'aurafilm' => 'AuraFilm', 'avebrasil' => 'AveBrasil', 'avedorama' => 'AveDorama',
        'avepremier' => 'AvePremier', 'aveturk' => 'AveTurk', 'axn sci fi' => 'AXN Sci-Fi',
        'azazel' => 'Azazel', 'azonfilm' => 'AzOnFilm', 'back board cinema' => 'Back Board Cinema',
        'badbajo' => 'BadBajo', 'badcatstudio' => 'BadCatStudio', 'bagichev' => 'А. Багичев',
        'baibako' => 'BaibaKo', 'bambooua' => 'BambooUA', 'banyan studio' => 'Banyan Studio',
        'barin101' => 'Barin101', 'bars macadams' => 'Bars MacAdams',
        'bbc saint petersburg' => 'BBC Saint-Petersburg', 'bd cee' => 'BD CEE', 'beniaffet' => 'BeniAffet',
        'berial' => 'Berial', 'binjak' => 'binjak', 'black street records' => 'Black Street Records',
        'bonsai studio' => 'Bonsai Studio', 'boльгa' => 'Boльгa', 'brain production' => 'Brain Production',
        'bravesound' => 'BraveSound', 'bravo records' => 'Bravo Records',
        'bravo records georgia' => 'Bravo Records', 'bti studios' => 'BTI Studios',
        'bubble dubbing company' => 'Bubble Dubbing Company', 'bukedub' => 'BukeDub',
        'byako records' => 'Byako Records', 'cactus team' => 'Cactus Team', 'cactusteam' => 'Cactus Team',
        'cartoon network' => 'Cartoon Network', 'casstudio' => 'CasStudio', 'cbs drama' => 'CBS Drama',
        'cdv' => 'CDV', 'chadov' => 'М. Чадов', 'chas ua' => 'CHAS.UA', 'cikava ideya' => 'Цікава Ідея',
        'cinema prestige' => 'Cinema Prestige', 'cinemaker' => 'Cinemaker',
        'cinemaset group' => 'CinemaSET GROUP', 'cinematone' => 'CinemaTone',
        'clan kaizoku' => 'Clan Kaizoku', 'cls media' => 'CLS Media', 'clubfate' => 'ClubFATE',
        'cmert' => 'Cmert', 'coldfilm' => 'ColdFilm', 'contentica' => 'Contentica',
        'coralmedia' => 'CoralMedia', 'cowabunga studio' => 'Cowabunga Studio', 'cp digital' => 'CP Digital',
        'cpi' => 'CPI Films', 'cpi films' => 'CPI Films', 'crazycatstudio' => 'CrazyCatStudio',
        'creative sound' => 'Creative Sound', 'crezastudio' => 'CrezaStudio', 'crunchyroll' => 'Crunchyroll',
        'cuba77' => 'Cuba77', 'd esarev' => 'Д. Есарев', 'd i m' => 'D.I.M.',
        'd nurmukhametov' => 'Д. Нурмухаметов', 'd yesarev' => 'Д. Есарев', 'd2lab' => 'D2Lab',
        'datynet' => 'datynet', 'ddv' => 'DDV', 'deadline' => 'DeadLine Studio',
        'deadline studio' => 'DeadLine Studio', 'deadsno' => 'DeadSno',
        'deeafilm studio' => 'DeeAFilm Studio', 'deep' => 'DEEP', 'demon' => '', 'den904' => 'den904',
        'description' => '', 'dextertv' => 'DexterTV', 'discovery' => '',
        'diva universal' => 'DIVA Universal', 'dniprofilm' => 'DniproFilm', 'doctor jocker' => 'А. Матвеев',
        'doctor joker' => 'А. Матвеев', 'dolsky' => 'А. Дольский', 'domashniy' => 'Домашний',
        'doublerec' => 'DoubleRec', 'dr joker' => 'А. Матвеев', 'dream cast' => 'Dream Cast',
        'dream records' => 'Dream Records', 'dreamcast' => 'Dream Cast', 'dreamrecords' => 'Dream Records',
        'dublicat' => 'DubLiCat', 'dvd classic' => 'DVD Classic', 'e lur e' => 'Е. Лурье',
        'east dream' => 'East Dream', 'eladiel' => 'Eladiel', 'elegia' => 'Elegia', 'elektri4ka' => '',
        'elrom' => 'Elrom', 'elysium' => '', 'emslie' => 'Emslie', 'epic team' => 'Epic Team',
        'eraserhead' => 'eraserhead', 'erogg' => 'erogg', 'esarev' => 'Д. Есарев', 'etv плюс' => 'ETV+',
        'eurochannel' => 'Eurochannel', 'extrabit' => 'Extrabit', 'f train' => 'F-TRAIN',
        'family fan edition' => 'Family Fan Edition', 'fanstudio' => 'FanStudio', 'fanvoxua' => 'FanVoxUA',
        'fdv' => 'FDV', 'fiendover' => 'fiendover', 'filiza' => 'Filiza Studio',
        'filiza studio' => 'Filiza Studio', 'film prestige' => 'Film Prestige', 'filmgate' => 'FilmGate',
        'filmsclub' => 'FilmsClub', 'firedub' => 'FireDub', 'flamestudio' => 'FlameStudio',
        'flarrow films' => 'Flarrow Films', 'flarrowfilms' => 'Flarrow Films', 'flux team' => 'Flux-Team',
        'focusstudio' => 'FocusStudio', 'focusx' => 'FocusX', 'force media' => 'Force Media',
        'forcemedia' => 'Force Media', 'fox' => 'FOX', 'fox crime' => 'Fox Crime', 'fox life' => 'Fox Life',
        'fox russia' => 'Fox Russia', 'foxcrime' => 'Fox Crime', 'foxlife' => 'Fox Life',
        'foxlight' => 'Foxlight', 'franek monk' => 'Franek Monk', 'gala voices' => 'Gala Voices',
        'galvid' => 'GalVid', 'garsu pasaulis' => 'Garsu Pasaulis', 'gavrilov' => 'А. Гаврилов',
        'gears media' => 'Gears Media', 'gemini' => '', 'general film' => 'General Film',
        'getsmart' => 'GetSmart', 'gezell studio' => 'Gezell Studio', 'ghostface' => 'Ghostface',
        'gladiolustv' => 'GladiolusTV', 'glanc' => 'П. Гланц', 'glanz' => 'П. Гланц', 'goblin' => 'Д. Пучков',
        'gold cinema' => 'Gold Cinema', 'goldteam' => 'GoldTeam', 'good people' => '',
        'goodtime media' => 'GoodTime Media', 'goodvideo' => 'GoodVideo', 'gorchakov' => 'В. Горчаков',
        'gostfilm' => 'GostFilm', 'gramalant' => 'Gramalant', 'gravi tv' => 'Gravi-TV',
        'greb creative' => 'Greb&Creative', 'green tea' => 'GREEN TEA',
        'greenрай studio' => 'GreenРай Studio', 'gremlin creative studio' => 'Gremlin Creative Studio',
        'hallmark' => 'Hallmark', 'hamster' => 'Hamster Studio', 'hamster studio' => 'Hamster Studio',
        'hamsterstudio' => 'Hamster Studio', 'haserillopaw' => 'HaseRiLLoPaW', 'hatoshi' => 'HATOSHI',
        'hdr' => 'HDRezka', 'hdrezka' => 'HDRezka', 'hdrezka studio' => 'HDRezka',
        'hellomickey production' => 'HelloMickey Production', 'highhopes' => 'HighHopes',
        'hiway grope' => 'HiWay Grope', 'hiwaygrope' => 'HiWay Grope', 'horizon studio' => 'Horizon Studio',
        'horror maker' => 'Horror Maker', 'hotvoice' => 'HotVoice', 'htb' => 'НТВ',
        'hungry inri' => 'hungry_inri', 'ictv' => 'ICTV', 'ideafilm' => 'IdeaFilm',
        'igvin solncekleshka' => 'IgVin & Solncekleshka', 'imageart' => 'ImageArt', 'inaridub' => 'InariDuB',
        'inter' => '', 'inter video' => 'Inter Video', 'interfilm' => 'Интер Фильм',
        'intra communications' => 'Intra Communications', 'ivi' => 'IVI', 'ivnet cinema' => 'Ivnet Cinema',
        'iнтер' => '', 'jakob bellmann' => 'Jakob Bellmann', 'jam' => 'JAM', 'jam club' => 'JAM',
        'janetta' => 'Janetta', 'jaskier' => 'Jaskier', 'jeferson' => 'JeFerSon', 'jetix' => 'Jetix',
        'jetvis' => 'Jetvis Studio', 'jetvis studio' => 'Jetvis Studio', 'jimmy j' => 'Jimmy J.',
        'jimmyj' => 'Jimmy J.', 'jivov' => 'Ю. Живов', 'joystudio' => 'JoyStudio',
        'julia prosenuk' => 'Julia Prosenuk', 'jwa project' => 'JWA Project',
        'k pozdnyakov' => 'К. Поздняков', 'kachur' => 'Kachur', 'kansai' => 'Kansai', 'karusel' => 'Карусель',
        'kerems13' => 'Kerems13', 'kerob' => 'Kerob', 'kerobtv' => 'Kerob', 'kiitos' => 'Kiitos',
        'kinogolos' => 'KinoGolos', 'kinomania' => 'Киномания', 'kinomanija' => 'Киномания',
        'kinomaniya' => 'Киномания', 'kinomanya' => 'Киномания', 'kinopoisk' => 'Кинопоиск',
        'kinopoisk hd' => 'Кинопоиск', 'kinoview' => 'KinoView', 'ko136' => 'ko136', 'kobayashi' => '',
        'koleso' => 'KOleso', 'korean craze' => 'Korean Craze', 'kosharaserials' => 'KosharaSerials',
        'kravec' => 'Кравец', 'kravec records' => 'Кравец', 'kravets' => 'Кравец',
        'kubik ko' => 'Кубик в Кубе', 'kubik v kube' => 'Кубик в Кубе', 'kubik3' => 'Кубик в Кубе',
        'kulzvuk studio' => 'Kulzvuk Studio', 'kuraj bambey' => 'Кураж-Бамбей',
        'kurazh bambey' => 'Кураж-Бамбей', 'kvk' => 'Кубик в Кубе', 'kолобок' => 'Колобок',
        'l volodarsky' => 'Л. Володарский', 'l0cdog' => 'L0cDoG', 'lakefilms' => 'LakeFilms',
        'lazer video' => 'Lazer Video', 'ldv' => 'LDV', 'le doyen' => 'LeDoyen',
        'le production' => 'LE-Production', 'ledoyen' => 'LeDoyen', 'levelin' => '',
        'levshafilm' => 'LevshaFilm', 'lexikc' => 'LeXiKC', 'lf' => 'LostFilm', 'libergal' => 'Г. Либергал',
        'liga hq' => 'Liga HQ', 'linefilm' => 'LineFilm', 'lisitz' => 'Lisitz',
        'lizard cinema' => 'Lizard Cinema', 'lizard cinema trade' => 'Lizard Cinema Trade',
        'loginoff' => 'Loginoff', 'logos' => 'Logos', 'lord32x' => 'Lord32x', 'lord666' => 'lord666',
        'lost film' => 'LostFilm', 'lostfilm' => 'LostFilm', 'lostfilmtv' => 'LostFilm',
        'lucky production' => 'Lucky Production', 'lupin' => '', 'm chadov' => 'М. Чадов',
        'm yarotsky' => 'М. Яроцкий', 'macross' => '', 'madrid' => '', 'mallorn' => 'Mallorn Studio',
        'mallorn studio' => 'Mallorn Studio', 'marclail' => 'Marclail', 'matveev' => 'А. Матвеев',
        'max nabokov' => 'Max Nabokov', 'maxmeister' => 'MaxMeister',
        'mc entertainment' => 'MC Entertainment', 'mcelroy' => 'McElroy', 'mega anime' => 'Mega-Anime',
        'melodic voice studio' => 'Melodic Voice Studio', 'melodicvoicestudio' => 'Melodic Voice Studio',
        'metalrus' => 'metalrus', 'mifsnaiper' => 'MifSnaiper', 'mihalev' => 'А. Михалёв',
        'mikail' => 'Mikail', 'mikhalev' => 'А. Михалёв', 'milirina' => 'Milirina', 'milvus' => 'Milvus',
        'miraidub' => 'MiraiDub', 'mixfilm' => 'MixFilm', 'movie dubbing' => 'Movie Dubbing',
        'moygolos' => 'MOYGOLOS', 'mrrose' => 'MrRose', 'mtv' => 'MTV', 'murzilka' => 'Murzilka',
        'muzoboz' => 'MUZOBOZ', 'mystery film' => 'Mystery Film', 'nastia' => 'Nastia',
        'national geographic' => '', 'nazel freya' => 'Nazel & Freya', 'neko64' => 'neko64',
        'nemahov' => 'Ю. Немахов', 'nemakhov' => 'Ю. Немахов', 'nemfilm' => 'NemFilm',
        'neo sound' => 'Neo-Sound', 'neoclassica' => 'Neoclassica', 'neon studio' => 'NEON Studio',
        'nevafilm' => 'Невафильм', 'new dream media' => 'New Dream Media', 'new records' => 'New Records',
        'newcomers' => 'NewComers', 'newdub' => 'NewDub', 'newstation' => 'NewStation',
        'newstudio' => 'NewStudio', 'nice media' => 'Nice-Media', 'nickelodeon' => 'Nickelodeon',
        'nika lenina' => 'Nika Lenina', 'nlo tv' => 'НЛО-TV', 'no future' => 'No-Future',
        'novafilm' => 'NovaFilm', 'novamedia' => 'Novamedia', 'ns' => 'NewStudio', 'octopus' => '',
        'oghra brown' => 'Oghra-Brown', 'omicron' => 'Omicron', 'omikron' => 'Omicron',
        'omskbird' => 'Omskbird', 'omskbird records' => 'Omskbird', 'oneinchnales' => 'Oneinchnales',
        'onibaku' => 'Onibaku', 'onisfilms' => 'OnisFilms', 'opendub' => 'OpenDub', 'opt' => 'ОРТ',
        'ort' => 'ОРТ', 'oslikt' => 'OSLIKt', 'ozeon' => 'Ozeon', 'ozz' => 'Ozz', 'ozz tv' => 'Ozz',
        'p glanc' => 'П. Гланц', 'p glantz' => 'П. Гланц', 'p glanz' => 'П. Гланц',
        'p kartsev' => 'П. Карцев', 'padet' => 'PaDet', 'paradox' => '',
        'paramount channel' => 'Paramount Channel', 'paramount comedy' => 'Paramount Comedy',
        'paramount pictures' => 'Paramount Pictures', 'parovoz production' => 'Parovoz Production',
        'pashaup' => 'PashaUp', 'paul bunyan' => 'Paul Bunyan', 'pazl voice' => 'Pazl Voice',
        'pcb translate' => 'PCB Translate', 'perevodman' => 'Переводман', 'persona99' => 'Persona99',
        'pifagor' => 'Пифагор', 'piratvoice' => 'PiratVoice', 'positive multimedia' => 'Позитив-Мультимедиа',
        'postmodern' => 'Postmodern', 'postmodern postproduction' => 'Postmodern',
        'pozdnyakov' => 'К. Поздняков', 'pozitiv' => 'Позитив-Мультимедиа',
        'pozitiv multimedia' => 'Позитив-Мультимедиа', 'profix media' => 'Profix Media',
        'project web mania' => 'Project Web Mania', 'prolix' => 'Prolix', 'psychotronic' => 'Psychotronic',
        'pythagor' => 'Пифагор', 'qtv' => 'QTV', 'radamant' => 'Radamant', 'raim' => 'RAIM',
        'rain death' => 'Rain Death', 'rainbow world' => 'Rainbow World', 'raindeath' => 'Rain Death',
        'rattlebox' => 'RATTLEBOX', 'realfake' => 'RealFake', 'reanimedia' => 'Reanimedia',
        'rebel voice' => 'Rebel Voice', 'recentfilms' => 'RecentFilms', 'red head sound' => 'Red Head Sound',
        'red media' => 'Red Media', 'reddiamond studio' => 'RedDiamond Studio', 'reddog' => 'RedDog',
        'redrussian1337' => 'RedRussian1337', 'ren tv' => 'РенТВ', 'renegade team' => 'Renegade Team',
        'rentv' => 'РенТВ', 'rg paravozik' => '', 'rhs' => 'Red Head Sound', 'ringo' => 'RinGo',
        'rizz fisher' => 'RiZZ_fisher', 'roxmarty' => 'RoxMarty', 'rumble' => '', 'ruscico' => 'RUSCICO',
        'rusfilm' => 'RusFilm', 'russianguy27' => 'RussianGuy27', 'ryabov' => 'С. Рябов', 'ryc99' => 'Ryc99',
        'saint sound' => 'Saint Sound', 'sakuranight' => 'SakuraNight', 'sam2007' => 'Sam2007',
        'satkur' => 'Satkur', 'sawyer888' => 'Sawyer888', 'sci fi russia' => 'Sci-Fi Russia',
        'sdi media' => 'SDI Media', 'sedorelli' => 'Sedorelli', 'selena' => 'Selena International',
        'selena international' => 'Selena International', 'sengoku' => '', 'seoul bay' => 'Seoul Bay',
        'sephiroth' => 'Sephiroth', 'seqw0' => 'seqw0', 'serbin' => 'Ю. Сербин', 'sesdizi' => 'SesDizi',
        'shachiburi' => 'Shachiburi', 'shadow dub project' => 'Shadow Dub Project', 'shaman' => '',
        'shinkadan' => 'ShinkaDan', 'shiza' => 'SHIZA Project', 'shiza project' => 'SHIZA Project',
        'showjet' => 'ShowJet', 'silversnow' => 'SilverSnow', 'skidub' => 'SkiDub',
        'sky voices' => 'Sky Voices', 'skyefilmtv' => 'SkyeFilmTV', 'smallfilm' => 'SmallFilm',
        'snk tv' => 'SNK-TV', 'snowrecords' => 'SnowRecords', 'softbox' => 'SoftBox',
        'soldluck2' => 'SOLDLUCK2', 'solod' => 'Solod', 'somewax' => 'SomeWax',
        'sony channel' => 'Sony Channel', 'sony sci fi' => 'Sony Sci-Fi', 'sony turbo' => 'Sony Turbo',
        'sorzteam' => 'SorzTeam', 'sound film' => 'Sound Film', 'sound group' => 'Sound-Group',
        'sovetromantica' => 'SovetRomantica', 'spacedust' => 'SpaceDust', 'srb' => 'Ю. Сербин',
        'ssvss' => 'ssvss', 'st elrom' => 'st.Elrom', 'steponee' => 'STEPonee', 'stevie' => 'Stevie',
        'stories man' => 'StorieS man', 'studio band' => 'Студийная Банда',
        'studio victory аsia' => 'Studio Victory Аsia', 'studioband' => 'Студийная Банда',
        'studiofilms' => 'StudioFilms', 'sunshine studio' => 'Sunshine Studio',
        'sunshinestudio' => 'Sunshine Studio', 'superbit' => '', 'suzaku' => 'Suzaku',
        'sweet couple' => 'sweet couple', 'sweet tv' => 'sweet.tv', 'syfy universal' => 'Syfy Universal',
        'tak treba' => 'Так Треба Продакшн', 'tak treba production' => 'Так Треба Продакшн',
        'tatamifilm' => 'TatamiFilm', 'tet' => 'TET', 'tf anigroup' => 'TF-AniGroup',
        'the kitchen russia' => 'The Kitchen Russia', 'the mike rec' => 'The Mike Rec.',
        'time media group' => 'Time Media Group', 'timecraft' => 'Timecraft', 'to dublyajnaya' => 'Дубляжная',
        'to dublyazhnaya' => 'Дубляжная', 'to4ka' => 'To4ka', 'to4katv' => 'To4ka',
        'tolstobrov' => 'А. Толстобров', 'total dvd' => 'Total DVD', 'tovbin' => 'Ю. Товбин',
        'train studio' => 'Train Studio', 'trainstudio' => 'Train Studio', 'trdlo studio' => 'Trdlo.studio',
        'trina d' => 'Trina_D', 'true dubbing studio' => 'True Dubbing Studio',
        'tumbler studio' => 'TUMBLER Studio', 'turkstar' => 'TurkStar', 'turok1990' => 'turok1990',
        'tv 1000' => 'TV1000', 'tv1000' => 'TV1000', 'tvs' => 'TVShows', 'tvshows' => 'TVShows',
        'twister' => '', 'tycoon' => '', 'tycoon studio' => 'Tycoon', 'ua dub' => 'UA-DUB',
        'uateam' => 'UATeam', 'uavoice' => 'UAVoice', 'ufdub' => 'UkraineFastDUB', 'ukraina' => '',
        'ukrainefastdub' => 'UkraineFastDUB', 'ukrdub' => 'UkrDub', 'ultradox' => '',
        'universal channel' => 'Universal Channel', 'universal russia' => 'Universal Russia',
        'urasiko' => 'Urasiko', 'v popov' => 'В. Попов', 'v zavgorodny' => 'В. Завгородний',
        'vashmax2' => 'VashMax2', 'vendetta' => '', 'vgm studio' => 'VGM Studio',
        'viasat history' => 'Viasat History', 'victeam' => 'VicTeam', 'victory films' => 'Victory-Films',
        'victoryfilms' => 'Victory-Films', 'video biz' => 'Video-BIZ', 'videobiz' => 'VideoBIZ',
        'videogram' => 'Videogram', 'vip premiere' => 'ViP Premiere', 'vip serial hd' => 'VIP Serial HD',
        'viruseproject' => 'ViruseProject', 'visanti vasaer' => 'visanti-vasaer', 'viz media' => 'VIZ Media',
        'vizgunov' => 'С. Визгунов', 'vo production' => 'VO-Production',
        'voice project' => 'Voice Project Studio', 'voice project studio' => 'Voice Project Studio',
        'voicepower' => 'VoicePower', 'voiz' => 'Voiz', 'volodarskiy' => 'Л. Володарский',
        'volodarsky' => 'Л. Володарский', 'volume 6 studio' => 'Volume-6 Studio',
        'vsi moscow' => 'VSI Moscow', 'vulpes vulpes' => 'Vulpes Vulpes', 'vulpesvulpes' => 'Vulpes Vulpes',
        'wakanim' => 'Wakanim', 'wayland team' => 'Wayland team', 'west video' => 'West Video',
        'westfilm' => 'WestFilm', 'wiadub' => 'WiaDUB', 'wvoice' => 'WVoice', 'xdub dorama' => 'XDUB Dorama',
        'xl media' => 'XL Media', 'xvidclub studio' => 'XvidClub Studio', 'y serbin' => 'Ю. Сербин',
        'yarotsky' => 'М. Яроцкий', 'yesarev' => 'Д. Есарев', 'yu nemahov' => 'Ю. Немахов',
        'yu serbin' => 'Ю. Сербин', 'yu zhivov' => 'Ю. Живов', 'zamez' => 'zamez', 'zee tv' => 'ZEE TV',
        'zendos' => 'Zendos', 'zerzia' => 'Zerzia', 'zhivov' => 'Ю. Живов', 'zm show' => 'ZM-Show',
        'zone studio' => 'Zone Studio', 'zone vision' => 'Zone Vision Studio',
        'zone vision studio' => 'Zone Vision Studio', 'zoomvision studio' => 'Zoomvision Studio',
        'а алексеев' => 'А. Алексеев', 'а багичев' => 'А. Багичев', 'а гаврилов' => 'А. Гаврилов',
        'а дольский' => 'А. Дольский', 'а карповский' => 'А. Карповский', 'а кашкин' => 'А. Кашкин',
        'а киреев' => 'А. Киреев', 'а марченко' => 'А. Марченко', 'а матвеев' => 'А. Матвеев',
        'а михалев' => 'А. Михалёв', 'а тимофеев' => 'А. Тимофеев', 'а толстобров' => 'А. Толстобров',
        'ааа sound' => 'AAA-Sound', 'абдулов' => 'Абдулов', 'абыгде' => 'АБыГДе', 'агапов' => 'Агапов',
        'акалит' => 'Акалит', 'акира' => '', 'акопян' => 'Акопян', 'акцент' => '',
        'алексеев' => 'А. Алексеев', 'алексей михалев' => 'А. Михалёв', 'альтера парс' => 'Альтера Парс',
        'альянс' => '', 'амальгама' => 'Амальгама', 'амс' => 'АМС',
        'анастасия гайдаржи' => 'Анастасия Гайдаржи', 'анатолий ашмарин' => 'Анатолий Ашмарин',
        'анатолий гусев' => 'Анатолий Гусев', 'анвад' => 'АнВад', 'андрей гаврилов' => 'А. Гаврилов',
        'андрей дольский' => 'А. Дольский', 'андрей питерский' => 'Андрей Питерский',
        'антонов николай' => 'Антонов Николай', 'анубис' => 'Анубис', 'арк тв' => 'Арк-ТВ',
        'арк тв studio' => 'АРК-ТВ Studio', 'артемьев' => 'Артемьев', 'архиазия' => 'АрхиАзия',
        'архитеатр' => 'АрхиТеатр', 'б федоров' => 'Б. Федоров', 'багичев' => 'А. Багичев',
        'бахурани' => 'Бахурани', 'белов' => 'Белов', 'бессонов' => 'Бессонов',
        'бестселлер' => 'Русский Бестселлер', 'бибиков' => 'Бибиков', 'бигыч' => 'Бигыч',
        'бойков' => 'Бойков', 'бусов глеб' => 'Бусов Глеб', 'в горчаков' => 'В. Горчаков',
        'в дохалов' => 'В. Дохалов', 'в завгородний' => 'В. Завгородний', 'в курдов' => 'В. Курдов',
        'в одне рило' => 'В одне рило', 'в попов' => 'В. Попов', 'в рукин' => 'В. Рукин',
        'в сонькин' => 'В. Сонькин', 'вартан дохалов' => 'В. Дохалов', 'варус видео' => 'Варус-Видео',
        'василий горчаков' => 'В. Горчаков', 'васильев' => 'Васильев', 'васильцев' => 'Васильцев',
        'васька куролесов' => 'Васька Куролесов', 'ващенко' => 'Ващенко', 'ващенко с' => 'Ващенко С.',
        'вгтрк' => 'ВГТРК', 'векшин' => 'Векшин', 'велес' => 'Велес', 'весельчак' => 'Весельчак',
        'видеобаза' => 'Видеобаза', 'видеоимпульс' => 'Видеоимпульс', 'видеопродакшн' => 'Видеопродакшн',
        'видеосервис' => 'Видеосервис', 'визгунов' => 'С. Визгунов', 'витя говорун' => 'Витя <говорун>',
        'вихров' => 'Вихров', 'войсовер' => 'Войсовер', 'володарский' => 'Л. Володарский',
        'вольга' => 'Вольга', 'воробьев сергей' => 'Воробьев Сергей', 'ворон' => '', 'воронцов' => 'Воронцов',
        'воротилин' => 'Воротилин', 'г либергал' => 'Г. Либергал', 'г румянцев' => 'Г. Румянцев',
        'гаврилов' => 'А. Гаврилов', 'гаевский' => 'Е. Гаевский', 'гей кино гид' => 'Гей Кино Гид',
        'герусов' => 'Герусов', 'гланц' => 'П. Гланц', 'глуховский' => 'Глуховский', 'гоблин' => 'Д. Пучков',
        'говинда рага' => 'Говинда Рага', 'горчаков' => 'В. Горчаков', 'готлиб' => 'Готлиб',
        'григорий либергал' => 'Г. Либергал', 'григорьев' => 'Григорьев', 'гризли' => '',
        'гундос' => 'Гундос', 'гуртом' => 'Гуртом', 'д есарев' => 'Д. Есарев',
        'д нурмухаметов' => 'Д. Нурмухаметов', 'д пучков' => 'Д. Пучков', 'д строев' => 'Д. Строев',
        'данилов' => 'Данилов', 'дасевич' => 'Дасевич', 'деваль видео' => 'Деваль Видео',
        'денис шадинский' => 'Денис Шадинский', 'деньщиков' => 'Деньщиков', 'держиморда' => 'Держиморда',
        'диктор cdv' => 'диктор CDV', 'дионик' => 'ДиоНиК', 'дмитрий есарев' => 'Д. Есарев',
        'дмитрий пучков' => 'Д. Пучков', 'дніпрофільм' => 'Дніпрофільм', 'дольский' => 'А. Дольский',
        'домашний' => '', 'дохалов' => 'В. Дохалов', 'дроздов' => 'Н. Дроздов',
        'другое кино' => 'Другое кино', 'дтв' => 'ДТВ', 'дубляжная' => 'Дубляжная', 'дубровин' => 'Дубровин',
        'дьяков' => 'Дьяков', 'дьяконов' => 'Дьяконов', 'е гаевский' => 'Е. Гаевский',
        'е гранкин' => 'Е. Гранкин', 'е лурье' => 'Е. Лурье', 'е рудой' => 'Е. Рудой',
        'е хрусталев' => 'Е. Хрусталёв', 'еа синема' => 'ЕА Синема', 'евгения лурье' => 'Е. Лурье',
        'екатеринбург арт' => 'Екатеринбург Арт', 'есарев' => 'Д. Есарев', 'живаго' => '',
        'живов' => 'Ю. Живов', 'журавлев' => 'Журавлев', 'жучков' => 'Жучков',
        'з ранку до ночі' => 'З Ранку До Ночі', 'завгородний' => 'В. Завгородний', 'заугаров' => 'Заугаров',
        'зебуро' => 'Зебуро', 'зереницын' => 'Зереницын', 'золотухин' => 'Золотухин',
        'и еремеев' => 'И. Еремеев', 'и клушин' => 'И. Клушин', 'и сафронов' => 'И. Сафронов',
        'и степанов' => 'И. Степанов', 'иванов' => 'Иванов', 'иванова и п пашут' => 'Иванова и П. Пашут',
        'игмар' => 'Игмар', 'иддк' => 'ИДДК', 'имидж арт' => 'Имидж-Арт', 'индия тв' => 'Индия ТВ',
        'интер' => '', 'интер фильм' => 'Интер Фильм', 'интерфильм' => 'Интер Фильм',
        'инфо фильм' => 'Инфо-фильм', 'ист вест' => 'Ист-Вест', 'к поздняков' => 'К. Поздняков',
        'к филонов' => 'К. Филонов', 'карапетян' => 'Карапетян', 'кармен видео' => 'Кармен Видео',
        'карповский' => 'А. Карповский', 'карусель' => '', 'карцев' => 'П. Карцев', 'кашкин' => 'А. Кашкин',
        'квадрат малевича' => 'Квадрат Малевича', 'кенс матвей' => 'Кенс Матвей', 'килька' => 'Килька',
        'кинолюкс' => 'Кинолюкс', 'киномания' => 'Киномания', 'кинопоиск' => 'Кинопоиск',
        'кинопремьера' => 'Кинопремьера', 'кипарис' => 'Кипарис', 'киреев' => 'А. Киреев',
        'кирилл сагач' => 'Кирилл Сагач', 'кириллица' => 'Кириллица', 'клюквин' => 'Клюквин',
        'козлов' => 'Козлов', 'колобок' => 'Колобок', 'колодій' => 'Колодій', 'комедия тв' => 'Комедия ТВ',
        'кондор' => 'Кондор', 'контентикoff' => 'КонтентикOFF', 'королев' => 'Королёв',
        'костюкевич' => 'Костюкевич', 'котов' => 'Котов', 'котова' => 'Котова', 'кошкин' => 'Кошкин',
        'кравец' => 'Кравец', 'ктк' => 'КТК', 'кубик в кубе' => 'Кубик в Кубе',
        'кубик в кубе ko' => 'Кубик в Кубе', 'кузнецов' => 'С. Кузнецов', 'кураж бамбей' => 'Кураж-Бамбей',
        'курасгречей' => 'КураСгречей', 'курдов' => 'В. Курдов', 'л володарский' => 'Л. Володарский',
        'лагута' => 'Лагута', 'лазер видео' => 'Лазер Видео', 'лайко' => 'Лайко', 'ланселап' => 'ЛанселаП',
        'лапшин' => 'Лапшин', 'латышев' => 'М. Латышев', 'лексикон' => 'Лексикон', 'ленфильм' => '',
        'леонид володарский' => 'Л. Володарский', 'леша прапорщик' => 'Леша Прапорщик',
        'либергал' => 'Г. Либергал', 'лизард' => 'Лизард', 'логинофф' => 'Логинофф', 'логос' => 'Logos',
        'лурье' => 'Е. Лурье', 'люсьена' => 'Люсьена', 'м латышев' => 'М. Латышев', 'м чадов' => 'М. Чадов',
        'м яроцкий' => 'М. Яроцкий', 'мадлен дюваль' => 'Мадлен Дюваль', 'максим жолобов' => 'Максим Жолобов',
        'максим латышев' => 'М. Латышев', 'максим логинофф' => 'Максим Логинофф',
        'малиновский' => 'Малиновский', 'малиновский сергей' => 'Малиновский Сергей',
        'марченко' => 'А. Марченко', 'мастер тэйп' => 'Мастер Тэйп', 'матвеев' => 'А. Матвеев',
        'махонько' => 'Махонько', 'машинский' => 'Машинский', 'медведев' => 'Медведев',
        'медиа комплекс' => 'Медиа-Комплекс', 'мельница' => 'Мельница', 'мика бондарик' => 'Мика Бондарик',
        'миняев' => 'Миняев', 'мительман' => 'Мительман', 'михаил чадов' => 'М. Чадов',
        'михаил яроцкий' => 'М. Яроцкий', 'михалев' => 'А. Михалёв', 'мишин' => 'Мишин',
        'мобильное телевидение' => 'Мобильное телевидение', 'морозов' => 'Морозов',
        'мост видео' => 'Мост-Видео', 'мосфильм' => '', 'мудров' => 'Мудров', 'муравский' => 'Муравский',
        'мьюзик трейд' => 'Мьюзик-трейд', 'н антонов' => 'Н. Антонов', 'н дроздов' => 'Н. Дроздов',
        'н золотухин' => 'Н. Золотухин', 'н кино' => 'Н-Кино',
        'н севастьянов seva1988' => 'Н.Севастьянов seva1988', 'набиев' => 'Набиев', 'назаров' => 'Назаров',
        'нарышкин' => 'Нарышкин', 'наталья гурзо' => 'Наталья Гурзо', 'нева 1' => 'Нева-1',
        'невафильм' => 'Невафильм', 'незупиняи продакшн' => 'НеЗупиняйПродакшн',
        'незупиняйпродакшн' => 'НеЗупиняйПродакшн', 'немахов' => 'Ю. Немахов', 'неоклассика' => 'Неоклассика',
        'несмертельное оружие' => 'Несмертельное оружие', 'никитин' => 'Никитин',
        'николай дроздов' => 'Н. Дроздов', 'нло tv' => 'НЛО-TV', 'новамедиа' => 'Novamedia',
        'новий канал' => 'Новий Канал', 'новый диск' => 'Новый диск', 'новый дубляж' => 'Новый Дубляж',
        'нтв' => 'НТВ', 'нтв плюс' => 'НТВ+', 'нтв профит' => 'НТВ-Профит', 'нтн' => 'НТН',
        'нурмухаметов' => 'Д. Нурмухаметов', 'оверлорд' => '', 'огородников' => 'Огородников',
        'омикрон' => 'Omicron', 'омікрон' => 'Omicron', 'орт' => 'ОРТ', 'останкино' => 'Останкино',
        'ох студия' => 'Ох! Студия', 'ошурков' => 'Ошурков', 'п гланц' => 'П. Гланц',
        'п карцев' => 'П. Карцев', 'парадиз' => '', 'пепелац' => 'Пепелац', 'первый канал' => 'Первый канал',
        'первый канал орт' => 'Первый канал ОРТ', 'первый твч' => 'Первый ТВЧ', 'переводман' => 'Переводман',
        'перец' => '', 'петербургский дубляж' => 'Петербургский дубляж', 'петербуржец' => 'Петербуржец',
        'петр гланц' => 'П. Гланц', 'пирамида' => '', 'пифагор' => 'Пифагор', 'плюсплюс' => 'ПлюсПлюс',
        'поздняков' => 'К. Поздняков', 'позитив' => 'Позитив-Мультимедиа',
        'позитив мультимедиа' => 'Позитив-Мультимедиа', 'попов' => 'В. Попов',
        'прайд продакшн' => 'Прайд Продакшн', 'премьер видео' => 'Премьер Видео',
        'премьер мультимедиа' => 'Премьер Мультимедиа', 'причудики' => 'Причудики', 'пронин' => 'Пронин',
        'прямостанов' => 'Прямостанов', 'пучков' => 'Д. Пучков', 'пятница' => '',
        'р янкелевич' => 'Р. Янкелевич', 'райдо' => 'Райдо', 'ракурс' => '',
        'реальный перевод' => 'Реальный перевод', 'рен тв' => 'РенТВ', 'рентв' => 'РенТВ', 'россия' => '',
        'ртр' => 'РТР', 'рудой' => 'Е. Рудой', 'рукин' => 'В. Рукин',
        'русский бестселлер' => 'Русский Бестселлер', 'русский репортаж' => 'Русский Репортаж',
        'рутилов' => 'Рутилов', 'руфилмс' => 'РуФилмс', 'рыбин' => 'Рыбин', 'рыжий пес' => 'Рыжий пес',
        'рябов' => 'С. Рябов', 'с визгунов' => 'С. Визгунов', 'с дьяков' => 'С. Дьяков',
        'с казаков' => 'С. Казаков', 'с кузнецов' => 'С. Кузнецов', 'с кузьмичев' => 'С. Кузьмичёв',
        'с лебедев' => 'С. Лебедев', 'с макашов' => 'С. Макашов', 'с р и' => 'С.Р.И', 'с рябов' => 'С. Рябов',
        'с щегольков' => 'С. Щегольков', 'сolumbia service' => 'Сolumbia Service',
        'сrunchyroll' => 'Crunchyroll', 'савченко' => 'Савченко', 'самарский' => 'Самарский',
        'санаев' => 'Санаев', 'саня белый' => 'Саня Белый', 'сб' => 'Студийная Банда',
        'св дубль' => 'СВ-Дубль', 'св кадр' => 'СВ-Кадр', 'св студия' => 'СВ-Студия', 'светла' => 'Светла',
        'севастьянов' => 'Севастьянов', 'селена интернешнл' => 'Selena International',
        'селена интернэшнл' => 'Selena International', 'семыкина юлия' => 'Семыкина Юлия',
        'сербин' => 'Ю. Сербин', 'сергей визгунов' => 'С. Визгунов', 'сергей дидок' => 'Сергей Дидок',
        'сергей рябов' => 'С. Рябов', 'синема трейд' => 'Синема Трейд', 'синема ус' => 'Синема УС',
        'синта рурони' => 'Синта Рурони', 'синхрон' => 'Синхрон', 'смирнов' => 'Смирнов', 'советский' => '',
        'сокира' => 'Сокира', 'сокуров' => '', 'солодухин' => 'Солодухин', 'сонотек' => 'Сонотек',
        'сонькин' => 'В. Сонькин', 'союз видео' => 'Союз Видео', 'союзмультфильм' => '',
        'спд сладкая парочка' => 'СПД - Сладкая парочка', 'старый бильбо' => 'Старый Бильбо',
        'стасюк' => 'Стасюк', 'стб' => 'СТБ', 'строев' => 'Д. Строев', 'струґачка' => 'Струґачка',
        'стс' => 'СТС', 'студии суверенного лепрозория' => 'Студии Суверенного Лепрозория',
        'студийная банда' => 'Студийная Банда', 'студия nls' => 'Студия NLS',
        'студия горького' => 'Студия Горького', 'студия колобок' => 'Колобок',
        'студия пиратского дубляжа' => 'Студия Пиратского Дубляжа', 'студия райдо' => 'Студия Райдо',
        'студия стартрек' => 'Студия <Стартрек>', 'студия трех' => 'Студия Трёх', 'супербит' => '',
        'сыендук' => 'Сыендук', 'т о друзей' => 'Т.О Друзей', 'тайкун' => 'Tycoon',
        'тайм медиа групп' => 'Time Media Group', 'так треба продакшн' => 'Так Треба Продакшн',
        'тактребапродакшн' => 'Так Треба Продакшн', 'тв xxi век' => 'ТВ XXI век', 'тв спб' => 'ТВ СПб',
        'твц' => 'ТВЦ', 'твч 1' => 'ТВЧ 1', 'тет' => 'ТеТ', 'тимофеев' => 'А. Тимофеев', 'тнт' => 'ТНТ',
        'то друзей' => 'ТО Друзей', 'то дубляжная' => 'Дубляжная', 'товбин' => 'Ю. Товбин',
        'толмачев' => 'Толмачев', 'толстобров' => 'А. Толстобров', 'тоникс медиа' => 'Тоникс Медиа',
        'тоніс' => 'Тоніс', 'точка zрения' => 'Точка Zрения', 'трамвай фильм' => 'Трамвай-фильм',
        'три крапки' => 'Три Крапки', 'украина' => '', 'україна' => '',
        'ульпаней эльром' => 'Ульпаней Эльром', 'уолт дисней компани' => 'Уолт Дисней Компани',
        'филонов' => 'К. Филонов', 'фильмэкспорт' => 'Фильмэкспорт', 'формат ab' => 'Формат AB',
        'фортуна фильм' => 'Фортуна-Фильм', 'хабар' => 'Хабар', 'хихидок' => 'Хихидок',
        'хихикающий доктор' => 'Хихикающий доктор', 'хлопушка' => 'Хлопушка',
        'хоррор мэйкер' => 'Хоррор Мэйкер', 'храм дорам тв' => 'Храм Дорам ТВ', 'хрусталев' => 'Хрусталев',
        'хуан рохас' => 'Хуан Рохас', 'цікава ідея' => 'Цікава Ідея', 'чадов' => 'М. Чадов',
        'четыре в квадрате' => 'Четыре в квадрате', 'чуев' => 'Чуев', 'шадинский' => 'Шадинский',
        'шварко' => 'Шварко', 'швецов' => 'Швецов', 'штамп' => 'Штамп', 'штамп дмитрий' => 'Штамп Дмитрий',
        'штейн' => 'Штейн', 'шуваев' => 'Шуваев', 'эй би видео' => 'Эй Би Видео',
        'элегия фильм' => 'Элегия фильм', 'электричка' => 'Электричка', 'ю живов' => 'Ю. Живов',
        'ю немахов' => 'Ю. Немахов', 'ю сербин' => 'Ю. Сербин', 'ю товбин' => 'Ю. Товбин',
        'юрий живов' => 'Ю. Живов', 'юрий немахов' => 'Ю. Немахов', 'юрий сербин' => 'Ю. Сербин',
        'я беллманн' => 'Я. Беллманн', 'яковлев' => 'Яковлев', 'янкелевич' => 'Янкелевич',
        'яроцкий' => 'М. Яроцкий', 'інтер' => '');
    return $d;
}

// Keys matched only as written.
function aio_voices_exact()
{
    static $e = array(
        'ams' => 'AMS', 'cpi' => 'CPI', 'deep' => 'DEEP', 'fox' => 'FOX', 'hdr' => 'HDr', 'htb' => 'HTB',
        'jam' => 'JAM', 'lf' => 'LF', 'ns' => 'NS', 'opt' => 'OPT', 'srb' => 'SRb', 'tet' => 'TET',
        'tvs' => 'TVS', 'сб' => 'СБ', 'тет' => 'ТеТ');
    return $e;
}
